<a href="https://colab.research.google.com/github/Ussainbasha123/Ussain/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
d=pd.read_csv("/content/titanic.csv")
d

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
d.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [4]:
d.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [5]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [6]:
d.columns[d.isna().any()]

Index(['Age', 'Cabin', 'Embarked'], dtype='object')

In [7]:
d['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [8]:
d['Embarked']=d['Embarked'].fillna(d['Embarked'])
d.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [9]:
m=(d["Sex"]=="female")&(d["Survived"]==1)
m

0      False
1       True
2       True
3       True
4      False
       ...
886    False
887     True
888    False
889    False
890    False
Length: 891, dtype: bool

In [10]:
e=pd.get_dummies(d["Embarked"])
e

         C      Q      S
0    False  False   True
1     True  False  False
2    False  False   True
3    False  False   True
4    False  False   True
..     ...    ...    ...
886  False  False   True
887  False  False   True
888  False  False   True
889   True  False  False
890  False   True  False

[891 rows x 3 columns]

In [11]:
d.groupby("Sex")["Survived"].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [12]:
d.groupby("Pclass")["Survived"].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [13]:
d['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [14]:
d['Age']=d['Age'].fillna(d['Age'].mean())
d['Age']

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: Age, Length: 891, dtype: float64

In [15]:
d.columns[d.isna().any()]

Index(['Cabin', 'Embarked'], dtype='object')

In [16]:
d.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,13.002015,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,22.000000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,29.699118,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,35.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [18]:
s=pd.get_dummies(d['Sex'])
d=pd.concat([d,s],axis=1)
d=d.drop("Sex",axis="columns")
d

KeyError: 'Sex'

In [20]:
d.head(10)

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,female,male
0,1,0,3,"Braund, Mr. Owen Harris",22.000000,1,0,A/5 21171,7.2500,NaN,S,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.000000,1,0,PC 17599,71.2833,C85,C,True,False
2,3,1,3,"Heikkinen, Miss. Laina",26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S,True,False
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.000000,1,0,113803,53.1000,C123,S,True,False
4,5,0,3,"Allen, Mr. William Henry",35.000000,0,0,373450,8.0500,NaN,S,False,True
5,6,0,3,"Moran, Mr. James",29.699118,0,0,330877,8.4583,NaN,Q,False,True
6,7,0,1,"McCarthy, Mr. Timothy J",54.000000,0,0,17463,51.8625,E46,S,False,True
7,8,0,3,"Palsson, Master. Gosta Leonard",2.000000,3,1,349909,21.0750,NaN,S,False,True
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",27.000000,0,2,347742,11.1333,NaN,S,True,False
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",14.000000,1,0,237736,30.0708,NaN,C,True,False

In [22]:
d.tail()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,female,male
886,887,0,2,"Montvila, Rev. Juozas",27.000000,0,0,211536,13.00,NaN,S,False,True
887,888,1,1,"Graham, Miss. Margaret Edith",19.000000,0,0,112053,30.00,B42,S,True,False
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",29.699118,1,2,W./C. 6607,23.45,NaN,S,True,False
889,890,1,1,"Behr, Mr. Karl Howell",26.000000,0,0,111369,30.00,C148,C,False,True
890,891,0,3,"Dooley, Mr. Patrick",32.000000,0,0,370376,7.75,NaN,Q,False,True

In [27]:

de={"name":["nisha","lisa","bosha","vijay","hussain","pradheepa","gavaskar","thaniyarasu","lokesh","anusha"],
"course":["DS","AI","AI","DS","DS","DS","AI","DA","DS","ML"]}
de

{'name': ['nisha',
  'lisa',
  'bosha',
  'vijay',
  'hussain',
  'pradheepa',
  'gavaskar',
  'thaniyarasu',
  'lokesh',
  'anusha'],
 'course': ['DS', 'AI', 'AI', 'DS', 'DS', 'DS', 'AI', 'DA', 'DS', 'ML']}

In [29]:
df=pd.DataFrame(de)
df

          name course
0        nisha     DS
1         lisa     AI
2        bosha     AI
3        vijay     DS
4      hussain     DS
5    pradheepa     DS
6     gavaskar     AI
7  thaniyarasu     DA
8       lokesh     DS
9       anusha     ML

In [31]:
d[(d['Survived']>25)&(d["Fare"]>50)]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked, female, male]
Index: []

In [34]:
d.sort_values('Fare')

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,female,male
815,816,0,1,"Fry, Mr. Richard",29.699118,0,0,112058,0.0000,B102,S,False,True
806,807,0,1,"Andrews, Mr. Thomas Jr",39.000000,0,0,112050,0.0000,A36,S,False,True
413,414,0,2,"Cunningham, Mr. Alfred Fleming",29.699118,0,0,239853,0.0000,NaN,S,False,True
481,482,0,2,"Frost, Mr. Anthony Wood ""Archie""",29.699118,0,0,239854,0.0000,NaN,S,False,True
302,303,0,3,"Johnson, Mr. William Cahoone Jr",19.000000,0,0,LINE,0.0000,NaN,S,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
438,439,0,1,"Fortune, Mr. Mark",64.000000,1,4,19950,263.0000,C23 C25 C27,S,False,True
341,342,1,1,"Fortune, Miss. Alice Elizabeth",24.000000,3,2,19950,263.0000,C23 C25 C27,S,True,False
737,738,1,1,"Lesurer, Mr. Gustave J",35.000000,0,0,PC 17755,512.3292,B101,C,False,True
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",36.000000,0,1,PC 17755,512.3292,B51 B53 B55,C,False,True
258,259,1,1,"Ward, Miss. Anna",35.000000,0,0,PC 17755,512.3292,NaN,C,True,False

In [37]:
d.sort_values("Fare",ascending=False)

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,female,male
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",36.000000,0,1,PC 17755,512.3292,B51 B53 B55,C,False,True
258,259,1,1,"Ward, Miss. Anna",35.000000,0,0,PC 17755,512.3292,NaN,C,True,False
737,738,1,1,"Lesurer, Mr. Gustave J",35.000000,0,0,PC 17755,512.3292,B101,C,False,True
88,89,1,1,"Fortune, Miss. Mabel Helen",23.000000,3,2,19950,263.0000,C23 C25 C27,S,True,False
438,439,0,1,"Fortune, Mr. Mark",64.000000,1,4,19950,263.0000,C23 C25 C27,S,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
806,807,0,1,"Andrews, Mr. Thomas Jr",39.000000,0,0,112050,0.0000,A36,S,False,True
815,816,0,1,"Fry, Mr. Richard",29.699118,0,0,112058,0.0000,B102,S,False,True
466,467,0,2,"Campbell, Mr. William",29.699118,0,0,239853,0.0000,NaN,S,False,True
481,482,0,2,"Frost, Mr. Anthony Wood ""Archie""",29.699118,0,0,239854,0.0000,NaN,S,False,True
822,823,0,1,"Reuchlin, Jonkheer. John George",38.000000,0,0,19972,0.0000,NaN,S,False,True

In [42]:
d['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [44]:
d['Survived'].value_counts(normalize=True)

Survived
0    0.616162
1    0.383838
Name: proportion, dtype: float64

In [45]:
d[d['female']& d["Survived"]]
d

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,female,male
0,1,0,3,"Braund, Mr. Owen Harris",22.000000,1,0,A/5 21171,7.2500,NaN,S,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.000000,1,0,PC 17599,71.2833,C85,C,True,False
2,3,1,3,"Heikkinen, Miss. Laina",26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S,True,False
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.000000,1,0,113803,53.1000,C123,S,True,False
4,5,0,3,"Allen, Mr. William Henry",35.000000,0,0,373450,8.0500,NaN,S,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",27.000000,0,0,211536,13.0000,NaN,S,False,True
887,888,1,1,"Graham, Miss. Margaret Edith",19.000000,0,0,112053,30.0000,B42,S,True,False
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",29.699118,1,2,W./C. 6607,23.4500,NaN,S,True,False
889,890,1,1,"Behr, Mr. Karl Howell",26.000000,0,0,111369,30.0000,C148,C,False,True
890,891,0,3,"Dooley, Mr. Patrick",32.000000,0,0,370376,7.7500,NaN,Q,False,True